-- The bounty zones with their level ranges from Classic and WoW: Forever. Every zone has one
-- boss; `loot` names the three mercenaries whose coins the boss drops, `gear` the mercenary
-- whose second (normal) or third (heroic) piece of equipment the first clear unlocks.

local _, ns = ...
ns.Mercenaries = ns.Mercenaries or {}
local MC = ns.Mercenaries

local function Z(id, continent, min, max, boss, pool, adds, loot, gearNormal, gearHeroic)
    return {
        id = id, continent = continent, min = min, max = max, boss = boss, pool = pool, adds = adds,
        loot = loot, gear = { normal = gearNormal, heroic = gearHeroic },
    }
end

MC.Zones = {
    elwynn = Z("elwynn", "ek", 1, 10, "hogger",
        { "kobold_vermin", "kobold_tunneler", "riverpaw_outrunner", "defias_thug", "murloc_streamrunner", "prowler" },
        { "riverpaw_gnoll", "riverpaw_outrunner", "prowler" }, { "renzik", "bolvar", "tirion" }, "bolvar", "renzik"),
    dunmorogh = Z("dunmorogh", "ek", 1, 10, "thermaplugg",
        { "frostmane_whelp", "frostmane_seer", "rockjaw_trogg", "leper_gnome", "ice_claw_bear" },
        { "leper_gnome", "leper_gnome", "leper_gnome" }, { "magni", "jaina", "cairne" }, "magni", "cairne"),
    tirisfal = Z("tirisfal", "ek", 1, 10, "whitemane",
        { "rattlecage_skeleton", "mindless_zombie", "scarlet_convert", "scarlet_missionary", "darkhound" },
        { "scarlet_monk", "scarlet_monk", "scarlet_missionary" }, { "sylvanas", "taelan", "benedictus" }, "sylvanas", "taelan"),
    teldrassil = Z("teldrassil", "kal", 1, 10, "melenas",
        { "grellkin", "timberling", "gnarlpine_ursa", "webwood_spider", "nightsaber" },
        { "grellkin", "grellkin", "timberling" }, { "tyrande", "shandris", "hamuul" }, "tyrande", "shandris"),
    durotar = Z("durotar", "kal", 1, 10, "zalazane",
        { "vile_familiar", "mottled_boar", "scorpid_worker", "kul_tiras_sailor", "durotar_tiger" },
        { "voodoo_troll", "voodoo_troll", "durotar_tiger" }, { "thrall", "voljin", "mankrik" }, "voljin", "thrall"),
    mulgore = Z("mulgore", "kal", 1, 10, "arrachea",
        { "plainstrider", "bristleback_quilboar", "palemane_tanner", "venture_laborer", "prairie_wolf" },
        { "prairie_wolf", "plainstrider", "prairie_wolf" }, { "magatha", "cairne", "hamuul" }, "hamuul", "magatha"),
    zephras = Z("zephras", "zephras", 1, 12, "lorthuna",
        { "shadowgale_shrieker", "shadowgale_shriekling", "shadowgale_ursera", "shadowgale_manticore", "drowned_skyborne" },
        { "shadowgale_ursera", "drowned_skyborne", "shadowgale_manticore" }, { "jaina", "tyrande", "shandris" }, "shandris", "jaina"),
    westfall = Z("westfall", "ek", 10, 20, "vancleef",
        { "defias_pillager", "defias_trapper", "harvest_golem", "riverpaw_gnoll", "fleshripper" },
        { "defias_blackguard", "defias_pillager", "defias_trapper" }, { "renzik", "eitrigg", "bolvar" }, "renzik", "bolvar"),
    lochmodan = Z("lochmodan", "ek", 10, 20, "galgosh",
        { "stonesplinter_trogg", "stonesplinter_seer", "mogrosh_ogre", "tunnel_rat", "dark_iron_dwarf", "mountain_buzzard" },
        { "stonesplinter_trogg", "stonesplinter_seer", "stonesplinter_trogg" }, { "magni", "eitrigg", "tirion" }, "eitrigg", "magni"),
    silverpine = Z("silverpine", "ek", 10, 20, "arugal",
        { "moonrage_whitescalp", "dalaran_apprentice", "rot_hide_gnoll", "shadowfang_moonwalker" },
        { "son_of_arugal", "shadowfang_moonwalker", "son_of_arugal" }, { "sylvanas", "jaina", "voljin" }, "jaina", "sylvanas"),
    darkshore = Z("darkshore", "kal", 10, 20, "murkdeep",
        { "greymist_coastrunner", "greymist_seer", "blackwood_pathfinder", "darkshore_thresher", "moonstalker" },
        { "greymist_coastrunner", "greymist_seer", "greymist_coastrunner" }, { "tyrande", "rexxar", "benedictus" }, "benedictus", "tyrande"),
    barrens = Z("barrens", "kal", 10, 25, "kodobane",
        { "razormane_thornweaver", "kolkar_wrangler", "witchwing_harpy", "venture_peon", "savannah_huntress", "kolkar_stormer" },
        { "kolkar_wrangler", "kolkar_stormer", "kolkar_wrangler" }, { "mankrik", "rexxar", "thrall" }, "mankrik", "rexxar"),
    redridge = Z("redridge", "ek", 15, 25, "gathilzogg",
        { "redridge_mongrel", "redridge_mystic", "blackrock_grunt", "blackrock_shadowcaster", "shadowhide_brute" },
        { "blackrock_grunt", "blackrock_shadowcaster", "blackrock_grunt" }, { "taelan", "eitrigg", "bolvar" }, "taelan", "eitrigg"),
    stonetalon = Z("stonetalon", "kal", 15, 27, "gerenzo",
        { "venture_logger", "venture_operator", "deepmoss_webspinner", "bloodfury_harpy", "grimtotem_ruffian" },
        { "venture_operator", "venture_logger", "venture_operator" }, { "magatha", "rexxar", "voljin" }, "magatha", "hamuul"),
    ashenvale = Z("ashenvale", "kal", 18, 30, "akumai",
        { "foulweald_warrior", "bleakheart_satyr", "blackfathom_tide_priestess", "blackfathom_myrmidon", "twilight_acolyte" },
        { "blackfathom_myrmidon", "twilight_acolyte", "blackfathom_tide_priestess" }, { "tyrande", "hamuul", "shandris" }, "rexxar", "voljin"),
    duskwood = Z("duskwood", "ek", 18, 30, "stitches",
        { "skeletal_warrior", "nightbane_shadow_weaver", "venom_web_spider", "bone_chewer", "plague_spreader" },
        { "plague_spreader", "skeletal_warrior", "bone_chewer" }, { "tirion", "taelan", "renzik" }, "tirion", "benedictus"),
    wetlands = Z("wetlands", "ek", 20, 30, "nekrosh",
        { "dragonmaw_grunt", "dragonmaw_shadowwarder", "mottled_raptor", "mosshide_gnoll", "bluegill_murloc" },
        { "dragonmaw_grunt", "dragonmaw_shadowwarder", "dragonmaw_grunt" }, { "magni", "thrall", "eitrigg" }, "thrall", "mankrik"),
    hillsbrad = Z("hillsbrad", "ek", 20, 30, "burnside",
        { "hillsbrad_footman", "hillsbrad_farmer", "syndicate_thief", "torn_fin_tidehunter", "gray_bear" },
        { "hillsbrad_councilman", "hillsbrad_footman", "hillsbrad_councilman" }, { "sylvanas", "jaina", "taelan" }, "cairne", "tirion"),
    thousandneedles = Z("thousandneedles", "kal", 25, 35, "arnak",
        { "galak_marauder", "galak_windchaser", "grimtotem_geomancer", "grimtotem_stomper", "crag_coyote", "saltstone_basilisk" },
        { "grimtotem_stomper", "grimtotem_geomancer", "grimtotem_stomper" }, { "magatha", "saurfang", "hamuul" }, "saurfang", nil),
    alterac = Z("alterac", "ek", 30, 40, "perenolde",
        { "syndicate_wizard", "syndicate_sentry", "crushridge_ogre", "crushridge_mage", "mountain_lion" },
        { "syndicate_sentry", "syndicate_wizard", "syndicate_sentry" }, { "jorach", "drekthar", "windsor" }, "jorach", "drekthar"),
    arathi = Z("arathi", "ek", 30, 40, "myzrael",
        { "boulderfist_ogre", "witherbark_troll", "witherbark_shadowcaster", "highland_strider", "thundering_exile", "burning_exile" },
        { "thundering_exile", "burning_exile", "cresting_exile" }, { "windsor", "saurfang", "jorach" }, nil, nil),
    desolace = Z("desolace", "kal", 30, 40, "theradras",
        { "gelkis_earthcaller", "magram_wrangler", "burning_blade_summoner", "hatefury_felsworn", "scorpashi_venomlash" },
        { "primordial_behemoth", "creeping_sludge", "primordial_behemoth" }, { "fandral", "drekthar", "natpagle" }, nil, nil),
    stranglethorn = Z("stranglethorn", "ek", 30, 45, "bangalash",
        { "bloodscalp_warrior", "bloodscalp_shaman", "skullsplitter_hunter", "kurzen_jungle_fighter", "stranglethorn_tigress" },
        { "stranglethorn_tigress", "elder_stranglethorn_tiger", "stranglethorn_tigress" }, { "natpagle", "voljin", "rexxar" }, nil, "jorach"),
    riverglades = Z("riverglades", "ek", 35, 45, "clugfist",
        { "bolderok_brute", "twilight_fanatic", "twilight_champion", "eastsea_raider", "mudfin_oracle", "wildplains_patriarch" },
        { "bolderok_brute", "twilight_champion", "bolderok_brute" }, { "natpagle", "windsor", "renzik" }, nil, nil),
    badlands = Z("badlands", "ek", 35, 45, "archaedas",
        { "dustbelcher_ogre", "dustbelcher_mystic", "ridge_huntress", "stonevault_seer", "dark_iron_dwarf" },
        { "earthen_custodian", "stone_keeper", "earthen_custodian" }, { "magni", "windsor", "saurfang" }, nil, nil),
    swampofsorrows = Z("swampofsorrows", "ek", 35, 45, "eranikus",
        { "marsh_inkspewer", "marsh_flesheater", "sawtooth_crocolisk", "fen_dweller", "atalai_warrior" },
        { "atalai_priest", "nightmare_wanderer", "atalai_warrior" }, { "fandral", "tyrande", "natpagle" }, nil, "natpagle"),
    dustwallow = Z("dustwallow", "kal", 35, 45, "onyxia",
        { "darkmist_spider", "firemane_scalebane", "firemane_ash_tail", "bloodfen_raptor", "drywallow_crocolisk" },
        { "onyxian_whelp", "onyxian_warder", "onyxian_whelp" }, { "saurfang", "natpagle", "jaina" }, "natpagle", nil),
    shendralas = Z("shendralas", "kal", 40, 45, "necrokhan",
        { "magram_necromancer", "magram_marauder", "decrepit_pylon_protector", "bristleback_skullcrusher", "blind_screecher", "outcast_marauder" },
        { "magram_necromancer", "outcast_necrokhan", "magram_marauder" }, { "fandral", "tyrande", "shandris" }, nil, nil),
    feralas = Z("feralas", "kal", 40, 50, "gordok",
        { "gordunni_ogre", "gordunni_shaman", "grimtotem_naturalist", "woodpaw_mystic", "feral_scar_yeti", "hatecrest_siren" },
        { "gordok_brute", "gordok_magelord", "gordok_brute" }, { "fandral", "drekthar", "rexxar" }, "fandral", nil),
    tanaris = Z("tanaris", "kal", 40, 50, "gahzrilla",
        { "wastewander_bandit", "wastewander_shadow_mage", "sandfury_hideskinner", "sandfury_shadowcaster", "dune_smasher", "southsea_pirate" },
        { "sandfury_soul_eater", "sandfury_blood_drinker", "sandfury_soul_eater" }, { "natpagle", "jorach", "renzik" }, nil, nil),
    hinterlands = Z("hinterlands", "ek", 40, 50, "hexx",
        { "witherbark_scalper", "witherbark_witch_doctor", "vilebranch_berserker", "vilebranch_shadowcaster", "silvermane_stalker" },
        { "vilebranch_berserker", "vilebranch_shadowcaster", "vilebranch_berserker" }, { "voljin", "drekthar", "rexxar" }, nil, nil),
    searinggorge = Z("searinggorge", "ek", 43, 50, "thaurissan",
        { "dark_iron_taskmaster", "dark_iron_geologist", "glassweb_spider", "heavy_war_golem", "magma_elemental" },
        { "anvilrage_guardsman", "shadowforge_flame_keeper", "anvilrage_guardsman" }, { "windsor", "magni", "jorach" }, "windsor", nil),
    azshara = Z("azshara", "kal", 45, 55, "azuregos",
        { "spitelash_warrior", "spitelash_siren", "highborne_apparition", "thunderhead_hippogryph", "legashi_satyr" },
        { "spitelash_warrior", "spitelash_siren", "spitelash_warrior" }, { "jaina", "tyrande", "fandral" }, nil, nil),
    blastedlands = Z("blastedlands", "ek", 45, 55, "kazzak",
        { "snickerfang_hyena", "redstone_basilisk", "felhound", "felguard_sentry", "shadowsworn_thug", "shadowsworn_cultist" },
        { "felguard_sentry", "felhound", "felguard_sentry" }, { "thrall", "saurfang", "eitrigg" }, nil, nil),
    felwood = Z("felwood", "kal", 48, 55, "banehollow",
        { "jaedenar_cultist", "jaedenar_adept", "jaedenar_hound", "deadwood_warrior", "deadwood_shaman", "toxic_horror" },
        { "jaedenar_darkweaver", "jaedenar_guardian", "jaedenar_darkweaver" }, { "fandral", "hamuul", "tyrande" }, nil, "fandral"),
    ungoro = Z("ungoro", "kal", 48, 55, "mosh",
        { "stegodon", "ravasaur_hunter", "frenzied_pterrordax", "ungoro_gorilla", "tar_creeper", "glutinous_ooze" },
        { "devilsaur", "ravasaur_hunter", "devilsaur" }, { "rexxar", "natpagle", "hamuul" }, nil, nil),
    burningsteppes = Z("burningsteppes", "ek", 50, 58, "rend",
        { "blackrock_soldier", "blackrock_warlock", "black_broodling", "firegut_ogre", "blackrock_worg" },
        { "chromatic_whelp", "blackhand_veteran", "blackhand_summoner" }, { "saurfang", "windsor", "thrall" }, nil, "saurfang"),
    westernplaguelands = Z("westernplaguelands", "ek", 51, 58, "gandling",
        { "skeletal_flayer", "diseased_wolf", "scarlet_mage", "scarlet_knight", "rotting_ghoul" },
        { "scholomance_necromancer", "risen_guard", "scholomance_dark_summoner" }, { "tirion", "taelan", "jorach" }, nil, nil),
    easternplaguelands = Z("easternplaguelands", "ek", 53, 60, "rivendare",
        { "plaguehound", "crypt_walker", "cursed_mage", "scourge_soldier", "gibbering_ghoul", "blighted_horror" },
        { "skeletal_berserker", "thuzadin_necromancer", "skeletal_berserker" }, { "tirion", "sylvanas", "windsor" }, nil, "windsor"),
    winterspring = Z("winterspring", "kal", 55, 60, "winterfall",
        { "winterfall_ursa", "winterfall_shaman", "frostsaber_huntress", "ice_thistle_yeti", "winterspring_screecher", "frostmaul_giant" },
        { "winterfall_den_watcher", "winterfall_shaman", "winterfall_den_watcher" }, { "drekthar", "jaina", "cairne" }, "drekthar", nil),
    silithus = Z("silithus", "kal", 55, 60, "cthun",
        { "hiveashi_drone", "hivezora_wasp", "dust_stormer", "twilight_geolord", "stonelash_pincer" },
        { "anubisath_sentinel", "qiraji_mindslayer", "anubisath_sentinel" }, { "tyrande", "fandral", "magni" }, nil, nil),
    hyjal = Z("hyjal", "kal", 58, 60, "archimonde",
        { "doomguard_commander", "crypt_walker", "felguard_elite", "jaedenar_legionnaire", "felhound", "gibbering_ghoul" },
        { "doomguard_commander", "felguard_sentry", "felguard_elite" }, { "tyrande", "thrall", "drekthar" }, nil, nil),
}

-- Travel order: by level, starting zones first.
MC.ZONE_ORDER = {
    "elwynn", "dunmorogh", "tirisfal", "teldrassil", "durotar", "mulgore", "zephras",
    "westfall", "lochmodan", "silverpine", "darkshore", "barrens", "redridge", "stonetalon",
    "ashenvale", "duskwood", "wetlands", "hillsbrad",
    "thousandneedles", "alterac", "arathi", "desolace", "stranglethorn", "riverglades", "badlands", "swampofsorrows",
    "dustwallow", "shendralas", "feralas", "tanaris", "hinterlands", "searinggorge", "azshara", "blastedlands",
    "felwood", "ungoro", "burningsteppes", "westernplaguelands", "easternplaguelands", "winterspring", "silithus", "hyjal",
}

-- Extra strength of each bounty's foes, so a party one level below the boss wins about 60 % of
-- the time against the bot's play (heroic: 40 % at level 59 without ranks or gear).
-- Tuned with tools/balance_mercenaries.py --tune (--heroic).
local POWER = {
    elwynn = -0.20, dunmorogh = 0.02, tirisfal = 0.11, teldrassil = 0.01, durotar = 0.24, mulgore = -0.03,
    zephras = 0.18, westfall = 0.03, lochmodan = 0.43, silverpine = 0.22, darkshore = 0.25, barrens = 0.24,
    redridge = 0.09, stonetalon = 0.61, ashenvale = 0.18, duskwood = 0.13, wetlands = 0.00, hillsbrad = 0.47,
}
local HEROIC_POWER = {
    elwynn = -0.02, dunmorogh = 0.30, tirisfal = 0.11, teldrassil = 0.30, durotar = 0.12, mulgore = 0.14,
    zephras = 0.09, westfall = 0.08, lochmodan = 0.20, silverpine = -0.09, darkshore = 0.16, barrens = 0.06,
    redridge = 0.09, stonetalon = 0.40, ashenvale = 0.09, duskwood = 0.03, wetlands = -0.08, hillsbrad = 0.20,
}
for id, zone in pairs(MC.Zones) do
    zone.power, zone.heroicPower = POWER[id] or 0, HEROIC_POWER[id] or 0
end
