"""Writes DarkmoonArcade/Games/Mercenaries/Translations.lua: python tools/gen_mercenaries_locale.py

The texts of Mercenaries in French, Spanish, Russian and Chinese come from
tools/locale/mercenaries_<lang>.txt (one "KEY<tab>text" per line, Lua escapes such as \\n kept).
Every text is checked against English: the same format codes (%d, %s, %%, |4...;) and colour
codes, so a translation can never break a string.format call. Names are taken from the client:
mercenaries from tools/npc_ids.json (Wowhead), zones from the client's area table. Zone stories
name their boss through %s; the game fills in the boss's name in the player's language.
"""
import csv
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "locale"
CACHE = ROOT / "tools" / ".cache"
OUT = ROOT / "DarkmoonArcade" / "Games" / "Mercenaries" / "Translations.lua"
LANGS = ["frFR", "esES", "ruRU", "zhCN"]

# Area IDs of the bounty zones in the client's AreaTable.
AREAS = {
    "elwynn": 12, "dunmorogh": 1, "tirisfal": 85, "teldrassil": 141, "durotar": 14, "mulgore": 215,
    "zephras": 16593, "westfall": 40, "lochmodan": 38, "silverpine": 130, "darkshore": 148, "barrens": 17,
    "redridge": 44, "stonetalon": 406, "ashenvale": 331, "duskwood": 10, "wetlands": 11, "hillsbrad": 267,
    "thousandneedles": 400, "alterac": 36, "arathi": 45, "desolace": 405, "shendralas": 16651,
    "riverglades": 16591, "stranglethorn": 33, "badlands": 3, "swampofsorrows": 8, "dustwallow": 15,
    "feralas": 357, "tanaris": 440, "hinterlands": 47, "searinggorge": 51, "azshara": 16, "blastedlands": 4,
    "felwood": 361, "ungoro": 490, "burningsteppes": 46, "westernplaguelands": 28, "easternplaguelands": 139,
    "winterspring": 618, "silithus": 1377, "hyjal": 616,
}
CONTINENTS = {"MC_CONTINENT_EK": 0, "MC_CONTINENT_KAL": 1}

CODE = re.compile(r"%[+]?\d*[ds]|%%|\|4[^;]*;|\|c[0-9a-fA-F]{8}|\|r")


def read(lang):
    rows = {}
    for line in (SRC / f"mercenaries_{lang}.txt").read_text(encoding="utf-8").splitlines():
        if line.strip():
            key, _, text = line.partition("\t")
            rows[key] = text
    return rows


def codes(text):
    # |4 plural forms differ by language; only their presence counts.
    return sorted("|4" if c.startswith("|4") else c for c in CODE.findall(text))


def check(lang, en, tr):
    problems = []
    for key, text in en.items():
        if key not in tr:
            problems.append(f"{lang}: missing {key}")
            continue
        want = codes(text)
        if key.startswith("MC_ZD_"):
            want = sorted(want + ["%s"])
        if codes(tr[key]) != want:
            problems.append(f"{lang}: codes differ in {key}: {codes(tr[key])} vs {want}")
    for key in tr:
        if key not in en:
            problems.append(f"{lang}: unknown key {key}")
    return problems


def area_names(lang):
    path = CACHE / f"AreaTable-{lang}.csv"
    rows = {r["ID"]: r["AreaName_lang"] for r in csv.DictReader(path.read_text(encoding="utf-8").splitlines())}
    return {zid: rows.get(str(area)) for zid, area in AREAS.items()}


def merc_names(lang):
    ids = json.loads((ROOT / "tools" / "npc_ids.json").read_text(encoding="utf-8"))
    by_npc = {v["id"]: v for v in ids.values() if v}
    mercs = re.findall(r'(\w+) = Merc\("\w+", "\w+", "\w+", (\d+),',
                       (ROOT / "DarkmoonArcade" / "Games" / "Mercenaries" / "Mercs.lua").read_text(encoding="utf-8"))
    out = {}
    for mid, npc in mercs:
        entry = by_npc.get(int(npc))
        name = entry and entry.get("names", {}).get(lang)
        if name:
            out[mid] = name
    return out


def lua_string(text):
    # Texts already carry their Lua escapes (\n); only quotes need care.
    return '"' + text.replace('"', '\\"') + '"'


def main():
    en = read("enUS")
    problems = []
    blocks = []
    for lang in LANGS:
        if not (SRC / f"mercenaries_{lang}.txt").exists():
            problems.append(f"{lang}: no translation file")
            continue
        tr = read(lang)
        problems += check(lang, en, tr)
        lines = [f'ns.AddStrings("{lang}", {{']
        lines += [f"    {k} = {lua_string(tr[k])}," for k in en if k in tr]
        for zid, name in area_names(lang).items():
            if name:
                lines.append(f"    MC_Z_{zid} = {lua_string(name)},")
        for mid, name in merc_names(lang).items():
            lines.append(f"    MC_M_{mid} = {lua_string(name)},")
        lines.append("})")
        blocks.append("\n".join(lines))
    if problems:
        print("\n".join(problems))
        if "--force" not in sys.argv:
            sys.exit(1)
    head = [
        "-- Generated by tools/gen_mercenaries_locale.py from tools/locale/; edit those files, not this one.",
        "-- French, Spanish, Russian and Chinese texts of Mercenaries.",
        "",
        "local _, ns = ...",
        "",
    ]
    OUT.write_text("\n".join(head) + "\n\n".join(blocks) + "\n", encoding="utf-8", newline="\n")
    print("wrote", OUT, "languages:", len(blocks))


if __name__ == "__main__":
    main()
