"""Writes DarkmoonArcade/Games/Mercenaries/MapArt.lua: python tools/gen_mercenaries_maps.py [build]

Reads the client's map tables (UiMap*, via wago.tools) for WoW: Forever and stores, per map, the
file IDs of its art tiles and, per zone, its rectangle on the continent map. With --preview the
tiles are also downloaded and stitched into PNGs under tools/.cache/maps for layout previews.
"""
import csv
import io
import json
import pathlib
import sys
import time
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = ROOT / "tools" / ".cache"
OUT = ROOT / "DarkmoonArcade" / "Games" / "Mercenaries" / "MapArt.lua"
BUILD = next((a for a in sys.argv[1:] if not a.startswith("--")), "1.60.1.70245")
UA = {"User-Agent": "Mozilla/5.0"}

CONTINENTS = {"ek": 1415, "kal": 1414}
# key: (uiMapID, continent key or None for a map of its own)
ZONES = {
    "elwynn": (1429, "ek"), "dunmorogh": (1426, "ek"), "tirisfal": (1420, "ek"), "westfall": (1436, "ek"),
    "lochmodan": (1432, "ek"), "silverpine": (1421, "ek"), "redridge": (1433, "ek"), "duskwood": (1431, "ek"),
    "wetlands": (1437, "ek"), "hillsbrad": (1424, "ek"), "riverglades": (2548, "ek"),
    "teldrassil": (1438, "kal"), "durotar": (1411, "kal"), "mulgore": (1412, "kal"), "darkshore": (1439, "kal"),
    "barrens": (1413, "kal"), "stonetalon": (1442, "kal"), "ashenvale": (1440, "kal"), "hyjal": (2482, "kal"),
    "shendralas": (2652, "kal"), "zephras": (2521, None),
    # Stage 2 and 3
    "thousandneedles": (1441, "kal"), "desolace": (1443, "kal"), "dustwallow": (1445, "kal"), "feralas": (1444, "kal"),
    "tanaris": (1446, "kal"), "azshara": (1447, "kal"), "felwood": (1448, "kal"), "ungoro": (1449, "kal"),
    "silithus": (1451, "kal"), "winterspring": (1452, "kal"),
    "alterac": (1416, "ek"), "arathi": (1417, "ek"), "badlands": (1418, "ek"), "blastedlands": (1419, "ek"),
    "westernplaguelands": (1422, "ek"), "easternplaguelands": (1423, "ek"), "hinterlands": (1425, "ek"),
    "searinggorge": (1427, "ek"), "burningsteppes": (1428, "ek"), "stranglethorn": (1434, "ek"), "swampofsorrows": (1435, "ek"),
}


def table(name):
    CACHE.mkdir(exist_ok=True)
    path = CACHE / f"{name}-{BUILD}.csv"
    if not path.exists():
        url = f"https://wago.tools/db2/{name}/csv?build={BUILD}"
        path.write_bytes(urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read())
    return list(csv.DictReader(path.read_text(encoding="utf-8").splitlines()))


def main():
    x_art = {r["UiMapID"]: r["UiMapArtID"] for r in table("UiMapXMapArt") if r["PhaseID"] == "0"}
    art = {r["ID"]: r for r in table("UiMapArt")}
    styles = {r["UiMapArtStyleID"]: r for r in table("UiMapArtStyleLayer") if r["LayerIndex"] == "0"}
    tiles = {}
    for r in table("UiMapArtTile"):
        if r["LayerIndex"] == "0":
            tiles.setdefault(r["UiMapArtID"], []).append((int(r["RowIndex"]), int(r["ColIndex"]), int(r["FileDataID"])))
    bounds = {}
    for r in table("UiMapAssignment"):
        if r["UiMapID"] != "947":
            bounds[int(r["UiMapID"])] = tuple(float(r[k]) for k in ("Region_0", "Region_1", "Region_3", "Region_4"))

    def art_of(map_id):
        art_id = x_art[str(map_id)]
        style = styles[art[art_id]["UiMapArtStyleID"]]
        t = sorted(tiles[art_id])
        return {
            "w": int(style["LayerWidth"]), "h": int(style["LayerHeight"]),
            "tw": int(style["TileWidth"]), "th": int(style["TileHeight"]),
            "cols": max(c for _, c, _ in t) + 1, "files": [f for _, _, f in t],
        }

    maps = {k: art_of(v) for k, v in CONTINENTS.items()}
    for key, (map_id, _) in ZONES.items():
        maps[key] = art_of(map_id)

    lines = [
        "-- Generated by tools/gen_mercenaries_maps.py from the client's map tables; do not edit.",
        "-- Map art tiles per map and every zone's rectangle on its continent (left, right, top, bottom).",
        "",
        "local _, ns = ...",
        "ns.Mercenaries = ns.Mercenaries or {}",
        "local MC = ns.Mercenaries",
        "",
        "MC.MapArt = {",
    ]
    for key, m in maps.items():
        files = ", ".join(str(f) for f in m["files"])
        lines.append(f"    {key} = {{ w = {m['w']}, h = {m['h']}, tw = {m['tw']}, th = {m['th']}, cols = {m['cols']}, files = {{ {files} }} }},")
    lines += ["}", "", "MC.ZoneMaps = {"]
    for key, (map_id, cont) in ZONES.items():
        if cont:
            zx0, zy0, zx1, zy1 = bounds[map_id]
            cx0, cy0, cx1, cy1 = bounds[CONTINENTS[cont]]
            # Map x runs against world y, map y against world x.
            rect = ((cy1 - zy1) / (cy1 - cy0), (cy1 - zy0) / (cy1 - cy0), (cx1 - zx1) / (cx1 - cx0), (cx1 - zx0) / (cx1 - cx0))
        else:
            rect, cont = (0.0, 1.0, 0.0, 1.0), key
        lines.append(f'    {key} = {{ map = {map_id}, continent = "{cont}", rect = {{ {rect[0]:.4f}, {rect[1]:.4f}, {rect[2]:.4f}, {rect[3]:.4f} }} }},')
    lines += ["}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("wrote", OUT)

    if "--preview" in sys.argv:
        from PIL import Image
        target = CACHE / "maps"
        target.mkdir(exist_ok=True)
        for key, m in maps.items():
            path = target / f"{key}.png"
            if path.exists():
                continue
            rows = len(m["files"]) // m["cols"]
            img = Image.new("RGB", (m["cols"] * m["tw"], rows * m["th"]))
            for i, fid in enumerate(m["files"]):
                url = f"https://wago.tools/api/casc/{fid}?download"
                data = urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read()
                r, c = divmod(i, m["cols"])
                img.paste(Image.open(io.BytesIO(data)).convert("RGB"), (c * m["tw"], r * m["th"]))
                time.sleep(0.2)
            img.crop((0, 0, m["w"], m["h"])).save(path)
            print("preview", key)


if __name__ == "__main__":
    main()
